# Generated by Django 5.2.5 on 2025-08-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codinome', models.CharField(max_length=50, unique=True)),
                ('nome_real', models.CharField(blank=True, max_length=100, null=True)),
                ('poder_principal', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('historia', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
